Replacing more exit statements with the common exit functions defined in xdg-utils-common
Instead of checking --help in every script moved a check for common commands
to xdg-utils-common and check the whole argument list for them.

diff --git a/xdg-utils/scripts/xdg-email b/xdg-utils/scripts/xdg-email
--- a/xdg-utils/scripts/xdg-email
+++ b/xdg-utils/scripts/xdg-email
@@ -43,40 +43,116 @@ Synopsis
 xdg-email [--help] [mailto-uri]
 
 _USAGE
-    exit 1
 }
-
-open_kde()
-{
-    kfmclient exec "$1"
-
-    exit $?
-}
-
-open_gnome()
-{
-    gnome-open "$1"
-
-    exit $?
-}
-
-
-open_xfce()
-{
-    exo-open "$1"
-
-    exit $?
-}
-
-
-[ x"$1" != x"" ] || usage
-[ x"$1" != x"--help" ] || usage
 
 #@xdg-utils-common@
 
 #----------------------------------------------------------------------------
 #   Common utility functions included in all XDG wrapper scripts
 #----------------------------------------------------------------------------
+
+#-------------------------------------------------------------
+# Exit script on successfully completing the desired operation
+
+exit_success()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    exit 0
+}
+
+
+#-----------------------------------------
+# Exit script on wrong number of arguments
+# prints usage information
+
+exit_failure_arg_count()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    usage
+
+    exit 1
+}
+
+
+#-----------------------------------
+# Exit script on malformed arguments
+# prints usage information
+
+exit_failure_arg_malformed()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    usage
+
+    exit 2
+}
+
+#-------------------------------------------------------------
+# Exit script on failure to locate necessary tool applications
+
+exit_failure_operation_impossible()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    exit 3
+}
+
+#-------------------------------------------------------------
+# Exit script on failure returned by a tool application
+
+exit_failure_operation_failed()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    exit 4
+}
+
+#----------------------------------------
+# Checks for shared commands, e.g. --help
+
+check_common_commands()
+{
+    while [ $# -gt 0 ] ; do
+        parm=$1
+        shift
+
+        case $parm in
+            --help)
+            usage
+            exit_success
+            ;;
+
+            --version)
+            echo "xdg-utils technical-preview"
+            exit_success
+            ;;
+        esac
+    done
+}
+
+check_common_commands "$@"
+
+#--------------------------------------
+# Checks for known desktop environments
+# set variable DE to the desktop environments name, lowercase
+
 detectDE()
 {
     if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
@@ -90,6 +166,43 @@ detectDE
 #----------------------------------------------------------------------------
 
 
+
+open_kde()
+{
+    kfmclient exec "$1"
+
+    if [ $? -eq 0 ]; then
+        exit_success
+    else
+        exit_failure_operation_failed
+    fi
+}
+
+open_gnome()
+{
+    gnome-open "$1"
+
+    if [ $? -eq 0 ]; then
+        exit_success
+    else
+        exit_failure_operation_failed
+    fi
+}
+
+
+open_xfce()
+{
+    exo-open "$1"
+
+    if [ $? -eq 0 ]; then
+        exit_success
+    else
+        exit_failure_operation_failed
+    fi
+}
+
+
+[ x"$1" != x"" ] || exit_failure_arg_count
 
 case "$DE" in
     kde)
@@ -105,7 +218,6 @@ case "$DE" in
     ;;
 
     *)
-    echo Sorry, no method available for opening "$1"
-    exit 2
+    exit_failure_operation_impossible "Sorry, no method available for opening" "$1"
     ;;
 esac
diff --git a/xdg-utils/scripts/xdg-su b/xdg-utils/scripts/xdg-su
--- a/xdg-utils/scripts/xdg-su
+++ b/xdg-utils/scripts/xdg-su
@@ -43,49 +43,116 @@ Synopsis
 xdg-su [--help] [-u user] [-c command]
 
 _USAGE
-    exit 1
 }
-
-su_kde()
-{
-    kdesu "$@"
-
-    exit $?
-}
-
-su_gnome()
-{
-    GSU=`which gnomesu 2>/dev/null`
-    if [ $? -eq 0 ] ; then
-        $GSU "$@"
-
-        exit $?
-    else
-        su_generic "$@"
-    fi
-}
-
-su_generic()
-{
-    XSU=`which xsu 2>/dev/null`
-    if [ $? -eq 0 ] ; then
-        $XSU "$@"
-
-        exit $?
-    else
-        echo Sorry, no graphical method available for invoking su "$*"
-        exit 2
-    fi
-}
-
-[ x"$1" != x"" ] || usage
-[ x"$1" != x"--help" ] || usage
 
 #@xdg-utils-common@
 
 #----------------------------------------------------------------------------
 #   Common utility functions included in all XDG wrapper scripts
 #----------------------------------------------------------------------------
+
+#-------------------------------------------------------------
+# Exit script on successfully completing the desired operation
+
+exit_success()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    exit 0
+}
+
+
+#-----------------------------------------
+# Exit script on wrong number of arguments
+# prints usage information
+
+exit_failure_arg_count()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    usage
+
+    exit 1
+}
+
+
+#-----------------------------------
+# Exit script on malformed arguments
+# prints usage information
+
+exit_failure_arg_malformed()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    usage
+
+    exit 2
+}
+
+#-------------------------------------------------------------
+# Exit script on failure to locate necessary tool applications
+
+exit_failure_operation_impossible()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    exit 3
+}
+
+#-------------------------------------------------------------
+# Exit script on failure returned by a tool application
+
+exit_failure_operation_failed()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    exit 4
+}
+
+#----------------------------------------
+# Checks for shared commands, e.g. --help
+
+check_common_commands()
+{
+    while [ $# -gt 0 ] ; do
+        parm=$1
+        shift
+
+        case $parm in
+            --help)
+            usage
+            exit_success
+            ;;
+
+            --version)
+            echo "xdg-utils technical-preview"
+            exit_success
+            ;;
+        esac
+    done
+}
+
+check_common_commands "$@"
+
+#--------------------------------------
+# Checks for known desktop environments
+# set variable DE to the desktop environments name, lowercase
+
 detectDE()
 {
     if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
@@ -99,6 +166,51 @@ detectDE
 #----------------------------------------------------------------------------
 
 
+
+su_kde()
+{
+    kdesu "$@"
+
+    if [ $? -eq 0 ]; then
+        exit_success
+    else
+        exit_failure_operation_failed
+    fi
+}
+
+su_gnome()
+{
+    GSU=`which gnomesu 2>/dev/null`
+    if [ $? -eq 0 ] ; then
+        $GSU "$@"
+
+        if [ $? -eq 0 ]; then
+            exit_success
+        else
+            exit_failure_operation_failed
+        fi
+    else
+        su_generic "$@"
+    fi
+}
+
+su_generic()
+{
+    XSU=`which xsu 2>/dev/null`
+    if [ $? -eq 0 ] ; then
+        $XSU "$@"
+
+        if [ $? -eq 0 ]; then
+            exit_success
+        else
+            exit_failure_operation_failed
+        fi
+    else
+        exit_failure_operation_impossible "Sorry, no graphical method available for invoking su" "$@"
+    fi
+}
+
+[ x"$1" != x"" ] || exit_failure_arg_count
 
 if [ x"$DE" = x"" ]; then
     XSU=`which xsu 2>/dev/null`
@@ -116,7 +228,11 @@ case "$DE" in
     su_gnome "$@"
     ;;
 
-    *)
+    generic)
     su_generic "$@"
+    ;;
+
+    *)
+    exit_failure_operation_impossible "Sorry, no graphical method available for invoking su" "$@"
     ;;
 esac
