Cleanup for safe quotes; add preliminary TET compatibility

diff --git a/xdg-utils/tests/testrun b/xdg-utils/tests/testrun
--- a/xdg-utils/tests/testrun
+++ b/xdg-utils/tests/testrun
@@ -19,25 +19,25 @@ TEST_LOG="xdg-test.log"
 run() {
 for TEST in $* ; do 
 	TOTAL=$((TOTAL+1))
-	if [ ! -f $TEST ]; then
-		echo -e "ERROR: $TEST not found" | tee -a $TEST_LOG
-	elif [ ! -x $TEST ]; then
-		echo -e "ERROR: $TEST not executable" | tee -a $TEST_LOG
+	if [ ! -f "$TEST" ]; then
+		echo -e "ERROR: $TEST not found" | tee -a "$TEST_LOG"
+	elif [ ! -x "$TEST" ]; then
+		echo -e "ERROR: $TEST not executable" | tee -a "$TEST_LOG"
 	else
 	# Create tempspace
 	mkworkdir
 	PREV_DIR=`pwd`
-	cd $TEST_WORK_DIR
+	cd "$TEST_WORK_DIR"
 	
 	# Run test
 	# TODO: some sort of interactive flag
-	eval "$PREV_DIR/$TEST" >> "$PREV_DIR/$TEST_LOG"
-	CODE=$?
+	("$PREV_DIR/$TEST") >> "$PREV_DIR/$TEST_LOG"
+	CODE="$?"
 	# Report result
-	if [ $CODE -eq 0 ] ; then
+	if [ "$CODE" -eq 0 ] ; then
 		PASS=$((PASS + 1))
 	else
-		case $CODE in
+		case "$CODE" in
 		1 ) RESULT=FAIL;;
 		5 ) RESULT=UNTESTED;;
 		7 ) RESULT=NORESULT;;
@@ -47,21 +47,21 @@ for TEST in $* ; do
 	fi
 	
 	# Remove tempspace (option to keep?)
-	cd $PREV_DIR
-	rm -rf $TEST_WORK_DIR
+	cd "$PREV_DIR"
+	rm -rf "$TEST_WORK_DIR"
 	unset TEST_WORK_DIR
 	fi
 done
 }
 
-echo "[`date`] TEST RUN START: $*" >> $TEST_LOG
+echo "[`date`] TEST RUN START: $*" >> "$TEST_LOG"
 
 for TS in $* ; do 
-	run `find $TS -name 't.*' -type f`
+	run `find "$TS" -name 't.*' -type f`
 done
 
-echo -n "[`date`] TEST RUN END: $* - " >> $TEST_LOG
-echo "$PASS of $TOTAL tests passed." | tee -a $TEST_LOG
+echo -n "[`date`] TEST RUN END: $* - " >> "$TEST_LOG"
+echo "$PASS of $TOTAL tests passed." | tee -a "$TEST_LOG"
 echo "See $TEST_LOG for details."
 
 if [ $(( $TOTAL - $PASS )) -gt 0 ]; then
@@ -69,5 +69,5 @@ if [ $(( $TOTAL - $PASS )) -gt 0 ]; then
 else
 	EC=0
 fi
-exit $EC
+exit "$EC"
 
